import { BenefitNodeSchema } from '../../types/benefit-node.js';
import { and, condition, or } from '../../types/rules.js';

const RAW_GERMANY_SEED_BENEFITS = [
  {
    id: 'de_federal_buergergeld',
    title: 'Bürgergeld (citizens\' income)',
    description: 'Federal basic income support for people who cannot cover living costs.',
    category: 'federal',
    geography: { country: 'DE' },
    eligibilityRules: and(
      condition('financial.netMonthlyIncome', 'lt', 1200),
      or(
        condition('employment.status', 'eq', 'unemployed'),
        condition('employment.status', 'eq', 'part-time')
      )
    ),
    benefitType: 'cash',
    valueEstimate: { min: 563, max: 1200, currency: 'EUR', period: 'monthly' },
    source: {
      authority: 'Bundesagentur für Arbeit / Jobcenter',
      url: 'https://www.arbeitsagentur.de/buergergeld',
      ingestionLayer: 'curated',
    },
    tags: ['income', 'jobcenter', 'stackable'],
    clusterTheme: 'employment transition',
    version: 1,
    status: 'active',
    eligibilityConfidenceBaseline: 0.8,
    scoringHints: {
      accessibilityWeight: 0.45,
      effortCostPenalty: 0.5,
      timeToReceiveWeeks: 6,
      retroactivePossible: true,
      stackableWith: ['de_federal_wohngeld'],
    },
  },
  {
    id: 'de_federal_wohngeld',
    title: 'Wohngeld (housing benefit)',
    description: 'Rent subsidy for low- and middle-income households.',
    category: 'federal',
    geography: { country: 'DE' },
    eligibilityRules: and(
      condition('housing.type', 'eq', 'rented'),
      condition('housing.monthlyRent', 'exists'),
      condition('financial.grossMonthlyIncome', 'lt', 3500)
    ),
    benefitType: 'subsidy',
    valueEstimate: { min: 100, max: 400, currency: 'EUR', period: 'monthly' },
    source: {
      authority: 'Bundesministerium für Wohnen',
      url: 'https://www.wohngeld.org',
      ingestionLayer: 'curated',
    },
    tags: ['housing', 'rent', 'stackable'],
    clusterTheme: 'housing cost relief',
    version: 1,
    status: 'active',
    scoringHints: {
      stackableWith: ['de_federal_buergergeld'],
      timeToReceiveWeeks: 10,
      retroactivePossible: false,
      accessibilityWeight: 0.55,
      effortCostPenalty: 0.35,
    },
  },
  {
    id: 'de_federal_kindergeld',
    title: 'Kindergeld (child benefit)',
    description: 'Monthly child allowance for families in Germany.',
    category: 'federal',
    geography: { country: 'DE' },
    eligibilityRules: condition('hasChildren', 'eq', true),
    benefitType: 'cash',
    valueEstimate: { min: 250, max: 250, currency: 'EUR', period: 'monthly' },
    source: {
      authority: 'Familienkasse',
      url: 'https://www.arbeitsagentur.de/familie-und-kinder/kindergeld',
      ingestionLayer: 'curated',
    },
    tags: ['children', 'family'],
    clusterTheme: 'family child support',
    version: 1,
    status: 'active',
    eligibilityConfidenceBaseline: 0.9,
  },
  {
    id: 'de_insurance_orthopedic_insoles',
    title: 'Krankenkasse reimbursement — orthopedic insoles',
    description: 'Statutory health insurance may reimburse prescribed orthopedic insoles.',
    category: 'insurance',
    geography: { country: 'DE' },
    eligibilityRules: and(
      condition('health.insuranceType', 'in', ['public']),
      or(
        condition('health.mobilityLimitations', 'exists'),
        condition('health.disabilityDegree', 'gte', 20)
      )
    ),
    benefitType: 'refund',
    valueEstimate: { min: 50, max: 180, currency: 'EUR', period: 'once' },
    source: {
      authority: 'GKV-Spitzenverband',
      url: 'https://www.gkv-spitzenverband.de',
      ingestionLayer: 'curated',
    },
    tags: ['health', 'mobility', 'reimbursement', 'retroactive'],
    clusterTheme: 'health mobility support',
    version: 1,
    status: 'active',
    scoringHints: {
      retroactivePossible: true,
      stackableWith: ['de_tax_medical_expenses'],
      accessibilityWeight: 0.7,
      effortCostPenalty: 0.2,
      timeToReceiveWeeks: 4,
    },
  },
  {
    id: 'de_tax_medical_expenses',
    title: 'Tax deduction — extraordinary medical expenses',
    description: 'Medical costs above the reasonable burden threshold may be tax-deductible.',
    category: 'tax',
    geography: { country: 'DE' },
    eligibilityRules: or(
      condition('health.chronicConditions', 'exists'),
      condition('health.disabilityDegree', 'gte', 20)
    ),
    benefitType: 'taxReduction',
    valueEstimate: { min: 200, max: 2500, currency: 'EUR', period: 'yearly' },
    source: {
      authority: 'Bundesfinanzministerium',
      url: 'https://www.bundesfinanzministerium.de',
      ingestionLayer: 'curated',
    },
    tags: ['tax', 'health', 'stackable'],
    clusterTheme: 'health mobility support',
    version: 1,
    status: 'active',
    scoringHints: {
      stackableWith: ['de_insurance_orthopedic_insoles'],
      timeToReceiveWeeks: 52,
      retroactivePossible: true,
      accessibilityWeight: 0.4,
      effortCostPenalty: 0.45,
    },
  },
  {
    id: 'de_transport_disability_pass',
    title: 'Severely disabled pass — transport discounts',
    description: 'Discounted public transport and mobility benefits with disability pass.',
    category: 'transport',
    geography: { country: 'DE' },
    eligibilityRules: condition('health.disabilityDegree', 'gte', 50),
    benefitType: 'discount',
    valueEstimate: { min: 200, max: 800, currency: 'EUR', period: 'yearly' },
    source: {
      authority: 'Verschiedene Verkehrsverbünde',
      url: 'https://www.integrationsaemter.de',
      ingestionLayer: 'curated',
    },
    tags: ['transport', 'mobility', 'disability'],
    clusterTheme: 'health mobility support',
    version: 1,
    status: 'active',
    scoringHints: {
      stackableWith: ['de_insurance_orthopedic_insoles'],
      accessibilityWeight: 0.65,
      effortCostPenalty: 0.25,
      timeToReceiveWeeks: 8,
      retroactivePossible: false,
    },
  },
  {
    id: 'de_federal_deutschlandticket',
    title: 'Deutschlandticket subsidy',
    description: 'Nationwide public transport pass — employer or municipal subsidies may apply.',
    category: 'transport',
    geography: { country: 'DE' },
    eligibilityRules: condition('employment.status', 'exists'),
    benefitType: 'discount',
    valueEstimate: { min: 180, max: 588, currency: 'EUR', period: 'yearly' },
    source: {
      authority: 'BMDV',
      url: 'https://www.deutschlandticket.de',
      ingestionLayer: 'curated',
    },
    tags: ['transport', 'commute'],
    version: 1,
    status: 'active',
  },
  {
    id: 'de_state_berlin_bildungspraemie',
    title: 'Berlin Bildungsprämie',
    description: 'State subsidy for approved continuing education courses in Berlin.',
    category: 'state',
    geography: { country: 'DE', state: 'BE', city: 'Berlin' },
    eligibilityRules: and(
      condition('location.city', 'eq', 'Berlin'),
      condition('education.courses', 'exists')
    ),
    benefitType: 'subsidy',
    valueEstimate: { min: 500, max: 1000, currency: 'EUR', period: 'once' },
    source: {
      authority: 'Senatsverwaltung Berlin',
      url: 'https://www.berlin.de',
      ingestionLayer: 'curated',
    },
    tags: ['education', 'weiterbildung'],
    clusterTheme: 'employment transition',
    version: 1,
    status: 'active',
  },
  {
    id: 'de_municipal_berlin_mietstabilisierung',
    title: 'Berlin rent stabilization bonus (example municipal program)',
    description: 'Municipal housing support for eligible renters in specific districts.',
    category: 'municipal',
    geography: { country: 'DE', state: 'BE', city: 'Berlin' },
    eligibilityRules: and(
      condition('housing.type', 'eq', 'rented'),
      condition('housing.monthlyRent', 'gt', 800),
      condition('financial.grossMonthlyIncome', 'lt', 2800)
    ),
    benefitType: 'subsidy',
    valueEstimate: { min: 50, max: 150, currency: 'EUR', period: 'monthly' },
    source: {
      authority: 'Berliner Wohnungsamt',
      url: 'https://www.berlin.de/lb/',
      ingestionLayer: 'curated',
    },
    tags: ['housing', 'municipal'],
    clusterTheme: 'housing cost relief',
    version: 1,
    status: 'active',
  },
  {
    id: 'de_education_bafög',
    title: 'BAföG student support',
    description: 'Federal student finance for school and university students.',
    category: 'education',
    geography: { country: 'DE' },
    eligibilityRules: condition('education.studentStatus', 'eq', true),
    benefitType: 'cash',
    valueEstimate: { min: 452, max: 934, currency: 'EUR', period: 'monthly' },
    source: {
      authority: 'BAföG Ämter',
      url: 'https://www.bafög.de',
      ingestionLayer: 'curated',
    },
    tags: ['education', 'student'],
    version: 1,
    status: 'active',
  },
  {
    id: 'de_ngo_caritas_emergency',
    title: 'Caritas emergency social support',
    description: 'NGO emergency assistance for food, utilities, and basic needs.',
    category: 'ngo',
    geography: { country: 'DE' },
    eligibilityRules: or(
      condition('financial.netMonthlyIncome', 'lt', 1000),
      condition('financial.savings', 'lt', 500)
    ),
    benefitType: 'freeService',
    valueEstimate: { min: 100, max: 600, currency: 'EUR', period: 'once' },
    source: {
      authority: 'Caritas Deutschland',
      url: 'https://www.caritas.de',
      ingestionLayer: 'curated',
    },
    tags: ['ngo', 'emergency'],
    version: 1,
    status: 'active',
    eligibilityConfidenceBaseline: 0.55,
  },
  {
    id: 'de_financial_riester',
    title: 'Riester retirement subsidy',
    description: 'Government allowances for eligible Riester pension contracts.',
    category: 'financial',
    geography: { country: 'DE' },
    eligibilityRules: and(
      condition('employment.status', 'exists'),
      condition('financial.grossMonthlyIncome', 'gt', 1200)
    ),
    benefitType: 'subsidy',
    valueEstimate: { min: 175, max: 350, currency: 'EUR', period: 'yearly' },
    source: {
      authority: 'Bundesministerium der Finanzen',
      url: 'https://www.bmf.de',
      ingestionLayer: 'curated',
    },
    tags: ['financial', 'retirement'],
    version: 1,
    status: 'active',
  },
  {
    id: 'de_retail_payback_bonus',
    title: 'Payback / loyalty program stacking',
    description: 'Retail loyalty programs with measurable savings on groceries and drugstore items.',
    category: 'retail',
    geography: { country: 'DE' },
    eligibilityRules: condition('location.country', 'eq', 'DE'),
    benefitType: 'discount',
    valueEstimate: { min: 50, max: 300, currency: 'EUR', period: 'yearly' },
    source: {
      authority: 'Payback / DeutschlandCard',
      url: 'https://www.payback.de',
      ingestionLayer: 'curated',
    },
    tags: ['retail', 'loyalty'],
    version: 1,
    status: 'active',
    eligibilityConfidenceBaseline: 0.95,
    scoringHints: {
      accessibilityWeight: 0.9,
      effortCostPenalty: 0.1,
      timeToReceiveWeeks: 1,
      retroactivePossible: false,
      stackableWith: [],
    },
  },
];

export const GERMANY_SEED_BENEFITS = RAW_GERMANY_SEED_BENEFITS.map((node) =>
  BenefitNodeSchema.parse(node)
);
