export { fetchLifeEventPlan } from './client';
export {
  formatLifeStateLabel,
  projectHomeNextSteps,
  projectLifeEventPage,
  projectActionSurface,
  EMPTY_ACTION_SURFACE,
  collectActionSurfaceNodeIds,
  buildExecutionSurface,
  buildExecutionSurfaceOrEmpty,
  buildExecutionStateLookup,
  isExecutionDisabled,
  EMPTY_EXECUTION_SURFACE,
  type HomeNextStepsProjection,
  type LifeEventPageProjection,
  type ActionSurfaceV1,
  type ExecutionAction,
  type ExecutionBlockedAction,
  type ExecutionSurfaceV1,
  mergeP4WithPlan,
  dedupeHomeSurfaces,
  buildHomePlanViewModelV2,
  type P4PlanOverlayV1,
  type HomeDedupResultV1,
  type HomePlanViewModelV2,
  type BuildHomePlanViewModelInput,
} from './presentation';
