export type {
  ModuleUIProjection,
  ModuleExecuteMeta,
  ModuleExecuteProjectionResponse,
  SanitizedAction,
  SanitizedActionKind,
  SanitizedActionPriority,
  SanitizedExplanation,
  SanitizedRecommendation,
  SanitizedRecommendationPriority,
} from './ModuleUIProjection.js';
export type { JsonSchema } from './JsonSchema.js';
export type { ContractSnapshot } from './ContractSnapshot.js';
export type {
  PublicModuleContract,
  PublicModuleContractMetadata,
  PublicModuleContractStatus,
} from './PublicModuleContract.js';
export type { NormalizedCapabilities } from './NormalizedCapabilities.js';
export { mapModuleStatus, type ModuleStatusInput } from './mapModuleStatus.js';
export { normalizeCapabilities } from './normalizeCapabilities.js';
export { resolveProductMetadata } from './moduleProductMetadata.js';
export {
  sanitizeAction,
  sanitizeActions,
  sanitizeExplanation,
  sanitizeRecommendation,
  sanitizeRecommendations,
} from './sanitizeModuleUI.js';
export { projectModuleUI } from './projectModuleUI.js';
export { buildContractSnapshot } from './buildContractSnapshot.js';
export {
  createContractSnapshotStore,
  type ContractSnapshotStore,
} from './ContractSnapshotStore.js';
export { bootstrapProductContractLayer } from './bootstrapProductContractLayer.js';
export { convertZodToJsonSchema } from './zodToJsonSchema.js';
export {
  projectModuleSchema,
  projectModuleCapabilities,
  type ModuleSchemaProjection,
} from './projectContractSnapshot.js';
export {
  projectPublicContract,
  projectPublicModuleContract,
  type ProjectPublicContractOptions,
} from './projectPublicContract.js';
export type {
  ExplanationFactor,
  ExplanationFactorType,
  ExplanationConfidence,
  ModuleExplanationView,
} from './ModuleExplanationView.js';
export {
  buildExplanationView,
  mapExplanationFactors,
  mapRecommendationReasons,
  mapActionReasons,
  aggregateExplanationConfidence,
} from './reason-mapping/index.js';
export type {
  ExecutionSnapshot,
  ActionCard,
  SnapshotRecommendation,
  ModuleSnapshotSummary,
  UiSnapshotProjection,
  SnapshotExecutionInput,
} from './snapshot/types.js';
export { projectExecutionSnapshot } from './snapshot/projectExecutionSnapshot.js';
export { projectActionCards } from './snapshot/projectActionCards.js';
export {
  projectModuleSummary,
  projectModuleSummaries,
  projectSnapshotRecommendations,
} from './snapshot/projectModuleSummary.js';
export { buildUiSnapshotProjection } from './snapshot/buildUiSnapshotProjection.js';
export {
  SupportedLanguageSchema,
  SUPPORTED_LANGUAGES,
  ThemePreferenceSchema,
  PRODUCT_NAME,
  PRODUCT_TAGLINE,
  type SupportedLanguage,
  type ThemePreference,
  type UiSnapshot,
  type UiSnapshotSession,
  type UiSnapshotProfile,
  type UiSnapshotFallback,
  type ModuleCatalogResponse,
  type SnapshotUserContextTransport,
  type LegacySnapshotContract,
} from './ui/index.js';
export {
  extractSchemaFields,
  deriveDefaultValues,
  mergeProfileIntoDefaults,
  type SchemaField,
  type SchemaFieldType,
} from './schema/deriveSchemaDefaults.js';
export {
  PROFILE_DOMAINS,
  ProfileDomainSchema,
  PROFILE_DOMAIN_REGISTRY,
  isProfileDomain,
  FACT_MUTATION_TYPES,
  META_MUTATION_TYPES,
  PREF_MUTATION_TYPES,
  MUTATION_TYPES,
  FactMutationTypeSchema,
  MetaMutationTypeSchema,
  PrefMutationTypeSchema,
  MutationTypeSchema,
  MUTATION_TYPE_REGISTRY,
  isFactMutationType,
  isMetaMutationType,
  isPersistentMutationType,
  MUTATION_INTENTS,
  MutationIntentSchema,
  MUTATION_INTENT_REGISTRY,
  MUTATION_TYPE_DEFAULT_INTENT,
  isMutationIntent,
  MutationSourceSchema,
  MUTATION_SOURCE_REGISTRY,
  SCENARIO_FIELD_IDS,
  ScenarioFieldIdSchema,
  SCENARIO_FIELD_REGISTRY,
  isScenarioFieldId,
  PERSISTENT_FACT_FIELD_IDS,
  PersistentFactFieldIdSchema,
  PERSISTENT_FACT_FIELD_REGISTRY,
  isPersistentFactFieldId,
  getFieldDefinition,
  getFieldsForDomain,
  MutationRequestSchema,
  MutationRequestPayloadSchema,
  DomainFactPayloadSchema,
  parseMutationRequest,
  safeParseMutationRequest,
  MutationEventSchema,
  MutationEventLogSchema,
  FieldDeltaSchema,
  parseMutationEvent,
  safeParseMutationEvent,
  ProfileRevisionSchema,
  ProfileRevisionFieldChangeSchema,
  parseProfileRevision,
  safeParseProfileRevision,
  UserProfileViewV1Schema,
  UserContextV1Schema,
  ProfileInsightViewV1Schema,
  USER_PROFILE_VIEW_SCHEMA_VERSION,
  PROFILE_INSIGHT_VIEW_SCHEMA_VERSION,
  parseUserProfileViewV1,
  safeParseUserProfileViewV1,
  parseUserContextV1,
  parseProfileInsightViewV1,
  safeParseProfileInsightViewV1,
  validatePersistentPayloadFields,
  assertPersistentFactFieldId,
  type ProfileDomain,
  type MutationType,
  type FactMutationType,
  type MetaMutationType,
  type PrefMutationType,
  type MutationIntent,
  type MutationSource,
  type ScenarioFieldId,
  type PersistentFactFieldId,
  type PersistentFactFieldDefinition,
  type MutationRequest,
  type ValidatedMutationRequest,
  type MutationRequestPayload,
  type DomainFactPayload,
  type PrefMutationPayload,
  type MutationEvent,
  type MutationEventLog,
  type FieldDelta,
  type ProfileRevision,
  type ProfileRevisionFieldChange,
  type UserProfileViewV1,
  type UserContextV1,
  type ProfileInsightViewV1,
  type DomainInsight,
  type DomainConfidence,
  type ConfidenceLevel,
  type MissingContextHint,
  type AdvisorySuggestion,
  type ProfileMirrorDomainSlug,
  type UserProfileDomainViews,
  type ProfileDomainFieldsMap,
  type MigrationDomainFields,
  type HousingDomainFields,
  type HouseholdDomainFields,
  type EmploymentDomainFields,
  type IncomeDomainFields,
  type HealthInsuranceDomainFields,
  type BenefitsDomainFields,
  type PreferencesDomainFields,
  type MutationValidationResult,
  LIFE_EVENT_PLAN_SCHEMA_VERSION,
  LifeEventPlanSchemaVersionSchema,
  LifeStateIdSchema,
  PlanningSeveritySchema,
  SecondaryConditionIdSchema,
  LifeEventNodeCategorySchema,
  LifeEventNodePrioritySchema,
  LifeActionKindSchema,
  LifeActionRefSchema,
  LifeEventPlanNodeSchema,
  LifeEventReasoningSchema,
  LifeEventPlanV1Schema,
  parseLifeEventPlanV1,
  safeParseLifeEventPlanV1,
  PLANNING_SEVERITY_BY_STATE,
  type LifeStateId,
  type PlanningSeverity,
  type SecondaryConditionId,
  type LifeEventNodeCategory,
  type LifeEventNodePriority,
  type LifeActionKind,
  type LifeActionRef,
  type LifeEventPlanNode,
  type LifeEventReasoning,
  type LifeEventPlanV1,
} from './profile/index.js';
