export {
  MODULE_CATALOG_VERSION,
  MODULE_CATALOG_V1,
  ECONOMIC_REALITY_MODULE_CATALOG_ENTRY,
  ECONOMIC_STATE_TRIGGER_CODE,
  EconomicStateTriggerCodeSchema,
  ModuleCatalogSurfaceSchema,
  OpenModuleEntrypointSchema,
  ModuleCatalogEntrySchema,
  ModuleCatalogV1Schema,
  findModuleCatalogEntry,
  listModuleCatalogEntries,
  matchesModuleTriggers,
  resolveTriggeredModules,
  buildModuleCatalogRoute,
  resolveCatalogTriggerEntrypoint,
  parseModuleCatalogV1,
  type ModuleCatalogV1,
  type ModuleCatalogEntryV1,
  type ModuleCatalogSurface,
  type ModuleTriggerContextV1,
  type EconomicStateTriggerCode,
  type OpenModuleEntrypoint,
} from './module-catalog.js';
export {
  ER_COPY_KEYS,
  ECONOMIC_REALITY_COPY_KEY_LIST,
  ECONOMIC_REALITY_COPY_EN,
  ECONOMIC_REALITY_COPY_DE,
  ECONOMIC_REALITY_COPY_RU,
  SYSTEM_INTENT_COPY_KEYS,
  SECTION_TYPE_COPY_KEYS,
  type EconomicRealityCopyKey,
} from '../i18n/index.js';
