export {
  PROFILE_DOMAINS,
  ProfileDomainSchema,
  PROFILE_DOMAIN_REGISTRY,
  isProfileDomain,
  type ProfileDomain,
  type ProfileDomainRegistryEntry,
} from './domains.js';

export {
  FACT_MUTATION_TYPES,
  META_MUTATION_TYPES,
  PREF_MUTATION_TYPES,
  MUTATION_TYPES,
  FactMutationTypeSchema,
  MetaMutationTypeSchema,
  PrefMutationTypeSchema,
  MutationTypeSchema,
  MUTATION_TYPE_REGISTRY,
  isFactMutationType,
  isMetaMutationType,
  isPersistentMutationType,
  type FactMutationType,
  type MetaMutationType,
  type PrefMutationType,
  type MutationType,
  type MutationTypeRegistryEntry,
} from './mutation-types.js';

export {
  MUTATION_INTENTS,
  MutationIntentSchema,
  MUTATION_INTENT_REGISTRY,
  MUTATION_TYPE_DEFAULT_INTENT,
  isMutationIntent,
  type MutationIntent,
  type MutationIntentRegistryEntry,
} from './mutation-intents.js';

export {
  MutationSourceKindSchema,
  SystemMutationReasonSchema,
  HeaderPrefFieldSchema,
  MutationSourceSchema,
  MUTATION_SOURCE_REGISTRY,
  type MutationSourceKind,
  type SystemMutationReason,
  type HeaderPrefField,
  type MutationSource,
  type MutationSourceRegistryEntry,
} from './mutation-source.js';

export {
  SCENARIO_FIELD_IDS,
  ScenarioFieldIdSchema,
  SCENARIO_FIELD_REGISTRY,
  isScenarioFieldId,
  type ScenarioFieldId,
  type ScenarioFieldDefinition,
  type ScenarioFieldValueMap,
} from './scenario-fields.js';

export {
  FieldSensitivitySchema,
  PERSISTENT_FACT_FIELD_IDS,
  PersistentFactFieldIdSchema,
  PERSISTENT_FACT_FIELD_REGISTRY,
  isPersistentFactFieldId,
  getFieldDefinition,
  getFieldsForDomain,
  type FieldSensitivity,
  type PersistentFactFieldId,
  type PersistentFactFieldDefinition,
} from './field-registry.js';

export {
  ResidencyStatusSchema,
  EmploymentStatusSchema,
  MaritalStatusSchema,
  InsuranceTypeSchema,
  TaxClassSchema,
  ChildAgeSchema,
  MigrationDomainFieldsSchema,
  HousingDomainFieldsSchema,
  HouseholdDomainFieldsSchema,
  EmploymentDomainFieldsSchema,
  IncomeDomainFieldsSchema,
  HealthInsuranceDomainFieldsSchema,
  BenefitsDomainFieldsSchema,
  PreferencesDomainFieldsSchema,
  ProfileDomainFieldsSchemaByDomain,
  DomainFactPayloadSchema,
  PrefMutationPayloadSchema,
  MutationRequestPayloadSchema,
  type ResidencyStatus,
  type EmploymentStatus,
  type MaritalStatus,
  type InsuranceType,
  type TaxClass,
  type ChildAge,
  type MigrationDomainFields,
  type HousingDomainFields,
  type HouseholdDomainFields,
  type EmploymentDomainFields,
  type IncomeDomainFields,
  type HealthInsuranceDomainFields,
  type BenefitsDomainFields,
  type PreferencesDomainFields,
  type ProfileDomainFieldsMap,
  type PrefFieldId,
  type PrefMutationPayload,
  type DomainFactPayload,
  type MutationRequestPayload,
} from './domain-field-types.js';

export {
  MutationRequestSchema,
  parseMutationRequest,
  safeParseMutationRequest,
  type MutationRequest,
  type ValidatedMutationRequest,
} from './mutation-request.js';

export {
  FieldDeltaOperationSchema,
  FieldDeltaSchema,
  MutationEventSchema,
  MutationEventLogSchema,
  parseMutationEvent,
  safeParseMutationEvent,
  type FieldDeltaOperation,
  type FieldDelta,
  type MutationEvent,
  type MutationEventLog,
} from './mutation-event.js';

export {
  ProfileRevisionFieldChangeSchema,
  ProfileRevisionSchema,
  parseProfileRevision,
  safeParseProfileRevision,
  type ProfileRevisionFieldChange,
  type ProfileRevision,
} from './profile-revision.js';

export {
  USER_PROFILE_VIEW_SCHEMA_VERSION,
  UserProfileViewSchemaVersionSchema,
  ProfileCompletenessSchema,
  UserProfileDomainViewsSchema,
  UserProfilePreferencesViewSchema,
  UserProfileViewV1Schema,
  UserContextV1Schema,
  parseUserProfileViewV1,
  safeParseUserProfileViewV1,
  parseUserContextV1,
  type ProfileCompleteness,
  type UserProfileDomainViews,
  type UserProfilePreferencesView,
  type UserProfileViewV1,
  type UserContextV1,
} from './user-profile-view.js';

export {
  PROFILE_INSIGHT_VIEW_SCHEMA_VERSION,
  ProfileInsightViewSchemaVersionSchema,
  ConfidenceLevelSchema,
  DomainConfidenceSchema,
  ProfileMirrorDomainSlugSchema,
  AdvisorySuggestionActionSchema,
  AdvisorySuggestionSchema,
  MissingContextHintSchema,
  DomainInsightSchema,
  ProfileInsightViewV1Schema,
  parseProfileInsightViewV1,
  safeParseProfileInsightViewV1,
  type ConfidenceLevel,
  type DomainConfidence,
  type ProfileMirrorDomainSlug,
  type AdvisorySuggestionAction,
  type AdvisorySuggestion,
  type MissingContextHint,
  type DomainInsight,
  type ProfileInsightViewV1,
} from './profile-insight-view.js';

export {
  LIFE_EVENT_PLAN_SCHEMA_VERSION,
  LifeEventPlanSchemaVersionSchema,
  LifeStateIdSchema,
  PlanningSeveritySchema,
  SecondaryConditionIdSchema,
  LifeEventNodeCategorySchema,
  LifeEventNodePrioritySchema,
  LifeActionKindSchema,
  LifeActionRefSchema,
  LifeEventPlanNodeSchema,
  LifeEventReasoningSchema,
  LifeEventPlanV1Schema,
  parseLifeEventPlanV1,
  safeParseLifeEventPlanV1,
  PLANNING_SEVERITY_BY_STATE,
  type LifeStateId,
  type PlanningSeverity,
  type SecondaryConditionId,
  type LifeEventNodeCategory,
  type LifeEventNodePriority,
  type LifeActionKind,
  type LifeActionRef,
  type LifeEventPlanNode,
  type LifeEventReasoning,
  type LifeEventPlanV1,
} from './life-event-plan.js';

export {
  ECONOMIC_EVALUATION_SCHEMA_VERSION,
  EconomicEvaluationSchemaVersionSchema,
  EconomicStateIdSchema,
  EconomicSupportSystemIdSchema,
  IncomeAxisSchema,
  EmploymentAxisSchema,
  InstitutionAxisSchema,
  EconomicAxesV1Schema,
  PlanConfidenceSchema,
  EconomicRuleIdSchema,
  EconomicBlockerIdSchema,
  AppliedRuleSchema,
  EconomicEvaluationV1Schema,
  parseEconomicEvaluationV1,
  safeParseEconomicEvaluationV1,
  type EconomicStateId,
  type EconomicSupportSystemId,
  type IncomeAxis,
  type EmploymentAxis,
  type InstitutionAxis,
  type EconomicAxesV1,
  type PlanConfidence,
  type EconomicRuleId,
  type EconomicBlockerId,
  type AppliedRule,
  type EconomicEvaluationV1,
} from './economic-evaluation.js';

export {
  ECONOMIC_GRAPH_CONTEXT_SCHEMA_VERSION,
  EconomicGraphContextSchemaVersionSchema,
  EconomicGraphIdSchema,
  EconomicGraphVariantSchema,
  GraphContextReasoningSchema,
  GraphContextV1Schema,
  STATE_TO_GRAPH_PRIMARY_SELECTOR,
  parseGraphContextV1,
  safeParseGraphContextV1,
  type EconomicGraphId,
  type EconomicGraphVariant,
  type GraphContextReasoning,
  type GraphContextV1,
} from './graph-context.js';

export {
  ECONOMIC_GRAPH_EXECUTION_SCHEMA_VERSION,
  EconomicGraphExecutionSchemaVersionSchema,
  EconomicSatisfactionKeySchema,
  NodeStateStatusSchema,
  NodeSatisfactionSchema,
  NodeStateV1Schema,
  GraphExecutionDerivedStateSchema,
  GraphExecutionReasoningSchema,
  GraphExecutionStateV1Schema,
  parseGraphExecutionStateV1,
  safeParseGraphExecutionStateV1,
  type EconomicSatisfactionKey,
  type NodeStateStatus,
  type NodeSatisfaction,
  type NodeStateV1,
  type GraphExecutionDerivedState,
  type GraphExecutionReasoning,
  type GraphExecutionStateV1,
} from './graph-execution-state.js';

export {
  ECONOMIC_ACTION_SET_SCHEMA_VERSION,
  EconomicActionSetSchemaVersionSchema,
  EconomicActionTypeSchema,
  EconomicExternalSystemSchema,
  EconomicSystemIntentSchema,
  EconomicActionPayloadSchema,
  EconomicActionConstraintsSchema,
  EconomicActionOriginSchema,
  EconomicActionV1Schema,
  EconomicActionSetMetadataSchema,
  EconomicActionSetV1Schema,
  parseEconomicActionSetV1,
  safeParseEconomicActionSetV1,
  type EconomicActionType,
  type EconomicExternalSystem,
  type EconomicSystemIntent,
  type EconomicActionPayload,
  type EconomicActionConstraints,
  type EconomicActionOrigin,
  type EconomicActionV1,
  type EconomicActionSetMetadata,
  type EconomicActionSetV1,
} from './economic-action-set.js';

export {
  ECONOMIC_PLAN_SCHEMA_VERSION,
  EconomicPlanSchemaVersionSchema,
  OrderingStrategySchema,
  EconomicPlanTrackV1Schema,
  EconomicPlanReasoningSchema,
  EconomicPlanV1Schema,
  parseEconomicPlanV1,
  safeParseEconomicPlanV1,
  TRACK_PRIORITY_BY_STRATEGY,
  type OrderingStrategy,
  type EconomicPlanTrackV1,
  type EconomicPlanReasoning,
  type EconomicPlanV1,
} from './economic-plan.js';

export {
  ECONOMIC_PRESENTATION_SCHEMA_VERSION,
  EconomicPresentationSchemaVersionSchema,
  PresentationSectionTypeSchema,
  PresentationUiTypeSchema,
  PresentationSeveritySchema,
  PresentationSourceTrackSchema,
  UiStrategySchema,
  PresentationCardV1Schema,
  PresentationSectionV1Schema,
  PresentationFocusV1Schema,
  EconomicPresentationMetadataSchema,
  EconomicPresentationV1Schema,
  parseEconomicPresentationV1,
  safeParseEconomicPresentationV1,
  type PresentationSectionType,
  type PresentationUiType,
  type PresentationSeverity,
  type PresentationSourceTrack,
  type UiStrategy,
  type PresentationCardV1,
  type PresentationSectionV1,
  type PresentationFocusV1,
  type EconomicPresentationMetadata,
  type EconomicPresentationV1,
} from './economic-presentation.js';

export {
  ECONOMIC_REALITY_API_VERSION,
  EconomicRealityApiVersionSchema,
  EconomicRealityPlanErrorCodeSchema,
  EconomicRealityPlanMetaSchema,
  EconomicRealityPlanResponseV1Schema,
  parseEconomicRealityPlanResponseV1,
  safeParseEconomicRealityPlanResponseV1,
  ECONOMIC_REALITY_PIPELINE_VERSION,
  type EconomicRealityPlanErrorCode,
  type EconomicRealityPlanMeta,
  type EconomicRealityPlanResponseV1,
} from './economic-reality-api.js';

export {
  validatePersistentPayloadFields,
  extractDomainFactFieldKeys,
  assertPersistentFactFieldId,
  type MutationValidationIssue,
  type MutationValidationResult,
} from './validation.js';
