import type {
  AtlasConnectionDefinition,
  AtlasNodeDefinition,
  AtlasSlideDefinition,
  JourneyStageId,
} from './types';

export const ATLAS_NODES: AtlasNodeDefinition[] = [
  { id: 'center', label: 'YOU ARE HERE', x: 400, y: 300, isCenter: true },
  { id: 'registration', label: 'Registration', x: 400, y: 118 },
  { id: 'housing', label: 'Housing', x: 168, y: 268 },
  { id: 'healthcare', label: 'Healthcare', x: 188, y: 468 },
  { id: 'finance', label: 'Finance', x: 400, y: 518 },
  { id: 'work', label: 'Work & Growth', x: 632, y: 268 },
  { id: 'community', label: 'Community', x: 612, y: 468 },
];

export const ATLAS_CONNECTIONS: AtlasConnectionDefinition[] = [
  { from: 'center', to: 'registration' },
  { from: 'center', to: 'housing' },
  { from: 'center', to: 'healthcare' },
  { from: 'center', to: 'finance' },
  { from: 'center', to: 'work' },
  { from: 'center', to: 'community' },
  { from: 'registration', to: 'housing' },
  { from: 'registration', to: 'finance' },
  { from: 'registration', to: 'healthcare' },
  { from: 'housing', to: 'work' },
  { from: 'housing', to: 'finance' },
  { from: 'healthcare', to: 'finance' },
  { from: 'finance', to: 'work' },
  { from: 'work', to: 'community' },
];

export const JOURNEY_STAGES: Array<{ id: JourneyStageId; label: string; subtitle: string }> = [
  { id: 'arrival', label: 'Arrival', subtitle: 'Week 1' },
  { id: 'setup', label: 'Setup', subtitle: 'Week 2–3' },
  { id: 'stabilize', label: 'Stabilize', subtitle: 'Month 1–2' },
  { id: 'build', label: 'Build', subtitle: 'Long term' },
];

export const ATLAS_SLIDES: AtlasSlideDefinition[] = [
  {
    id: 'orientation',
    index: 0,
    label: '01',
    headline: 'Your new life.',
    headlineAccent: 'Mapped.',
    supporting:
      'Arrival Atlas helps you understand everything you need to build a stable life in a new country.',
    cta: 'Enter Your Atlas',
    ctaHref: '/modules/life-event',
    focusNode: null,
    emphasizedConnections: [],
    completedNodes: [],
    blockedNodes: [],
    journeyStage: 'arrival',
    sidePanel: {
      title: 'Orientation',
      status: 'Overview',
      remaining: [
        'Understand domains',
        'Understand dependencies',
        'Know your position',
      ],
      tone: 'overview',
    },
    mapZoom: 1,
  },
  {
    id: 'registration',
    index: 1,
    label: '02',
    headline: 'Understand the',
    headlineAccent: 'big picture.',
    supporting: 'Bureaucracy becomes a navigable path — not a wall of unknown steps.',
    cta: 'Start Registration',
    ctaHref: '/modules/life-event',
    focusNode: 'registration',
    emphasizedConnections: [
      ['registration', 'housing'],
      ['registration', 'finance'],
      ['center', 'registration'],
    ],
    completedNodes: [],
    blockedNodes: [],
    journeyStage: 'setup',
    sidePanel: {
      title: 'Registration',
      status: 'In Progress',
      remaining: ['Address confirmation', 'Insurance update', 'City registration'],
      nextStep: 'Book appointment',
      tone: 'progress',
    },
    mapZoom: 1.06,
  },
  {
    id: 'housing',
    index: 2,
    label: '03',
    headline: 'Navigate with',
    headlineAccent: 'clarity.',
    supporting: 'Housing is the foundation — see what it unlocks across your map.',
    cta: 'Explore Housing',
    ctaHref: '/profile',
    focusNode: 'housing',
    emphasizedConnections: [
      ['housing', 'registration'],
      ['housing', 'work'],
      ['center', 'housing'],
    ],
    completedNodes: ['registration'],
    blockedNodes: [],
    journeyStage: 'setup',
    sidePanel: {
      title: 'Housing',
      status: 'In Progress',
      remaining: ['Find apartment', 'Rental contract', 'Registration update'],
      nextStep: 'Review housing checklist',
      tone: 'progress',
    },
    mapZoom: 1.08,
  },
  {
    id: 'healthcare',
    index: 3,
    label: '04',
    headline: 'Take action with',
    headlineAccent: 'confidence.',
    supporting: 'Healthcare fits into the system — connected, visible, and actionable.',
    cta: 'Open Healthcare',
    ctaHref: '/profile',
    focusNode: 'healthcare',
    emphasizedConnections: [
      ['healthcare', 'registration'],
      ['healthcare', 'finance'],
      ['center', 'healthcare'],
    ],
    completedNodes: ['registration', 'housing'],
    blockedNodes: [],
    journeyStage: 'stabilize',
    sidePanel: {
      title: 'Healthcare',
      status: 'In Progress',
      remaining: ['Activate insurance', 'Choose doctor', 'Initial checkup'],
      nextStep: 'Confirm coverage',
      tone: 'progress',
    },
    mapZoom: 1.08,
  },
  {
    id: 'finance',
    index: 4,
    label: '05',
    headline: 'Track your',
    headlineAccent: 'progress.',
    supporting: 'Build financial stability step by step — with every connection visible.',
    cta: 'View Economic Reality',
    ctaHref: '/modules/economic-reality',
    focusNode: 'finance',
    emphasizedConnections: [
      ['finance', 'work'],
      ['finance', 'registration'],
      ['center', 'finance'],
    ],
    completedNodes: ['registration', 'housing', 'healthcare'],
    blockedNodes: [],
    journeyStage: 'stabilize',
    sidePanel: {
      title: 'Finance',
      status: 'In Progress',
      remaining: ['Open bank account', 'Understand benefits', 'Build budget plan'],
      nextStep: 'Review economic guidance',
      tone: 'progress',
    },
    mapZoom: 1.1,
  },
  {
    id: 'growth',
    index: 5,
    label: '06',
    headline: "You're not just arriving.",
    headlineAccent: "You're building.",
    supporting: 'The map opens toward growth — opportunities, network, and long-term stability.',
    cta: 'Continue Your Plan',
    ctaHref: '/modules/life-event',
    focusNode: 'work',
    emphasizedConnections: [
      ['work', 'community'],
      ['work', 'finance'],
      ['center', 'work'],
    ],
    completedNodes: ['registration', 'housing', 'healthcare', 'finance', 'community'],
    blockedNodes: [],
    journeyStage: 'build',
    sidePanel: {
      title: 'Work & Growth',
      status: 'Ready',
      remaining: [
        'Explore opportunities',
        'Grow your network',
        'Improve your skills',
      ],
      nextStep: 'Open your life plan',
      tone: 'future',
    },
    mapZoom: 1.12,
  },
];
