import type { ModuleExecuteProjectionResponse } from '@arrival-atlas/product-contract';

export type {
  ActionCard,
  ExecutionSnapshot,
  ExplanationFactor,
  JsonSchema,
  ModuleCatalogResponse,
  ModuleExecuteMeta,
  ModuleExecuteProjectionResponse,
  ModuleExplanationView,
  ModuleSchemaProjection,
  ModuleSnapshotSummary,
  ModuleUIProjection,
  MutationRequest,
  NormalizedCapabilities,
  PublicModuleContract,
  PublicModuleContractMetadata,
  PublicModuleContractStatus,
  SchemaField,
  SchemaFieldType,
  SnapshotRecommendation,
  SanitizedRecommendation,
  SupportedLanguage,
  ThemePreference,
  UiSnapshot,
  UiSnapshotFallback,
  UiSnapshotProjection,
  UiSnapshotSession,
  UserContextV1,
  UserProfileViewV1,
  ProfileInsightViewV1,
  LifeEventPlanV1,
  LifeEventPlanNode,
  LifeEventReasoning,
  LifeActionRef,
  ProfileDomain,
  DomainInsight,
  MissingContextHint,
} from '@arrival-atlas/product-contract';

export {
  PRODUCT_NAME,
  PRODUCT_TAGLINE,
  SUPPORTED_LANGUAGES,
  SupportedLanguageSchema,
  ThemePreferenceSchema,
  deriveDefaultValues,
  extractSchemaFields,
  mergeProfileIntoDefaults,
  parseUserContextV1,
  parseProfileInsightViewV1,
  parseLifeEventPlanV1,
  safeParseLifeEventPlanV1,
} from '@arrival-atlas/product-contract';

export type ModuleExecuteResponse = ModuleExecuteProjectionResponse;
