import type { ModuleExecuteProjectionResponse } from '@arrival-atlas/product-contract';

export type {
  ActionCard,
  ExecutionSnapshot,
  ExplanationFactor,
  JsonSchema,
  ModuleCatalogResponse,
  ModuleExecuteMeta,
  ModuleExecuteProjectionResponse,
  ModuleExplanationView,
  ModuleSchemaProjection,
  ModuleSnapshotSummary,
  ModuleUIProjection,
  MutationRequest,
  NormalizedCapabilities,
  PublicModuleContract,
  PublicModuleContractMetadata,
  PublicModuleContractStatus,
  SchemaField,
  SchemaFieldType,
  SnapshotRecommendation,
  SanitizedRecommendation,
  SupportedLanguage,
  ThemePreference,
  UiSnapshot,
  UiSnapshotFallback,
  UiSnapshotProjection,
  UiSnapshotSession,
  UserContextV1,
  UserProfileViewV1,
  ProfileInsightViewV1,
  LifeEventPlanV1,
  LifeEventPlanNode,
  LifeEventReasoning,
  LifeActionRef,
  EconomicRealityPlanResponseV1,
  EconomicRealityPlanErrorCode,
  EconomicEvaluationV1,
  EconomicStateId,
  PlanConfidence,
  EconomicBlockerId,
  GraphContextV1,
  GraphExecutionStateV1,
  EconomicActionSetV1,
  EconomicActionV1,
  EconomicPlanV1,
  EconomicPresentationV1,
  PresentationSectionV1,
  PresentationCardV1,
  PresentationFocusV1,
  PresentationSectionType,
  PresentationUiType,
  ProfileDomain,
  DomainInsight,
  MissingContextHint,
  ConfidenceLevel,
  ProfileMirrorDomainSlug,
  LifeStateId,
  SecondaryConditionId,
} from '@arrival-atlas/product-contract';

export {
  PRODUCT_NAME,
  PRODUCT_TAGLINE,
  SUPPORTED_LANGUAGES,
  SupportedLanguageSchema,
  ThemePreferenceSchema,
  deriveDefaultValues,
  extractSchemaFields,
  mergeProfileIntoDefaults,
  parseUserContextV1,
  parseProfileInsightViewV1,
  parseLifeEventPlanV1,
  safeParseLifeEventPlanV1,
  parseEconomicRealityPlanResponseV1,
  safeParseEconomicRealityPlanResponseV1,
  ECONOMIC_REALITY_PIPELINE_VERSION,
  MODULE_CATALOG_V1,
  ECONOMIC_REALITY_MODULE_CATALOG_ENTRY,
  ECONOMIC_STATE_TRIGGER_CODE,
  findModuleCatalogEntry,
  matchesModuleTriggers,
  buildModuleCatalogRoute,
  type ModuleCatalogV1,
  type ModuleCatalogEntryV1,
  type ModuleTriggerContextV1,
  type OpenModuleEntrypoint,
  type EconomicStateTriggerCode,
  ER_COPY_KEYS,
  ECONOMIC_REALITY_COPY_EN,
} from '@arrival-atlas/product-contract';

export type ModuleExecuteResponse = ModuleExecuteProjectionResponse;
